// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230818050106_Initial DB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdmin");

                    b.Property<DateTime>("UserLastLoginDateTime")
                        .HasColumnType("date")
                        .HasColumnName("UserLastLogin");

                    b.Property<string>("UserLastLoginIpAddress")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)")
                        .HasColumnName("UserLastLoginIpAddress");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("Nvarchar(500)")
                        .HasColumnName("UserPassword");

                    b.Property<string>("UserSalt")
                        .IsRequired()
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserSalt");

                    b.HasKey("Id")
                        .HasName("pk_UserId");

                    b.ToTable("LoginUser");
                });
#pragma warning restore 612, 618
        }
    }
}
